SHARE = /usr/share
GNUARM = $(SHARE)/gnuarm-$(GNUARM_VERSION)
GNUARM_ELF = $(GNUARM)/arm-elf
GNUARM_BIN=$(GNUARM)/bin
GNUARM_BIN1=$(GNUARM_ELF)/bin
GNUARM_INC1 = $(GNUARM_ELF)/include
GNUARM_LIB = $(GNUARM_ELF)/lib
GNUARM_SYS_INC = $(GNUARM_ELF)/sys-include
GNUARM_INC2 = $(GNUARM)/include
GNUARM_MAN = $(GNUARM)/man
GNUARM_SHARE = $(GNUARM)/share
GNUARM_LIBEXEC = $(GNUARM)/libexec
GNUARM_LIB2 = $(GNUARM)/lib/gcc/arm-elf/$(GNUARM_VERSION)
PHILIPS_INC = $(GNUARM_INC2)/philips

GNUARM_INCLUDES = -I $(GNUARM_SYS_INC) -I $(PHILIPS_INC) -I $(GNUARM_INC1) -I $(GNUARM_INC2)
GNUARM_LIBS = -L $(GNUARM_LIB) -L $(GNUARM_LIB2)
GNUARM_LIB_GCC = $(GNUARM_LIB2)/libgcc.a
